services:
  db:
    image: postgres:latest
    shm_size: 2g
    environment:
      POSTGRES_DB: FastAPIProject
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./init_core_db.sql:/docker-entrypoint-initdb.d/init_core_db.sql
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c work_mem=128MB  
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d FastAPIProject" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:1234@db/FastAPIProject
      
  smtp:
    image: namshi/smtp
    ports:
      - "1025:25"
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend  

  orthanc:
    build:
      context: ./orthanc_config
    ports:
      - "8042:8042"
    volumes:
      - ./pacs_data:/pacs-storage
      - ./orthanc_config/handlers.py:/etc/orthanc/handlers.py
      - ./orthanc_config/requirements.txt:/etc/orthanc/requirements.txt
    depends_on:
      - db
    environment:
      DICOM_WEB_PLUGIN_ENABLED: "true"
      GDCM_PLUGIN_ENABLED: "true"
      ORTHANC_WEB_VIEWER_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      #OSIMIS_WEB_VIEWER1_ALPHA_PLUGIN_ENABLED: "true"
      PYTHON_PLUGIN_ENABLED: "true"
      WORKLISTS_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"

volumes:
  postgres_data:
  orthanc_data: