"""Added the initial migration

Revision ID: 0b97dd4ae41b
Revises: 5261f86b6c8c
Create Date: 2024-12-23 14:38:13.829404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b97dd4ae41b'
down_revision: Union[str, None] = '5261f86b6c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
