"""Added the initial migration

Revision ID: 2050dc820ac3
Revises: b4c9946a82fa
Create Date: 2024-12-23 11:23:55.850665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2050dc820ac3'
down_revision: Union[str, None] = 'b4c9946a82fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
