"""Added the initial migration

Revision ID: 41918e55cdbc
Revises: cf3ee768d89b
Create Date: 2024-12-23 15:40:14.352722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41918e55cdbc'
down_revision: Union[str, None] = 'cf3ee768d89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
