"""Added the initial migration

Revision ID: 63c85e1a0ebc
Revises: d5f5cd604716
Create Date: 2024-12-25 13:06:50.547235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c85e1a0ebc'
down_revision: Union[str, None] = 'd5f5cd604716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
