"""Added the initial migration

Revision ID: 726ccdf4681b
Revises: 0e3da97b8a70
Create Date: 2024-12-27 09:07:15.112300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726ccdf4681b'
down_revision: Union[str, None] = '0e3da97b8a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
