"""Added the initial migration

Revision ID: 7c6277dcb1b8
Revises: 9d25a1bda82a
Create Date: 2025-01-06 18:48:57.001226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6277dcb1b8'
down_revision: Union[str, None] = '9d25a1bda82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
