"""Added the initial migration

Revision ID: 7c7c2fe9e5f4
Revises: 89d4b08afae6
Create Date: 2024-12-21 12:36:42.943272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7c2fe9e5f4'
down_revision: Union[str, None] = '89d4b08afae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
