"""Added the initial migration

Revision ID: 94bc95bf82ee
Revises: 1727e6d4d01a
Create Date: 2024-12-20 17:20:46.698185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bc95bf82ee'
down_revision: Union[str, None] = '1727e6d4d01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
