"""Added the initial migration

Revision ID: 9bb1b36e2d4f
Revises: e0692b6833ab
Create Date: 2024-12-23 15:24:32.385528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb1b36e2d4f'
down_revision: Union[str, None] = 'e0692b6833ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
