"""Added the initial migration

Revision ID: b2b204cbbdc2
Revises: 3b50e7f4302a
Create Date: 2024-12-25 10:04:04.557851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b204cbbdc2'
down_revision: Union[str, None] = '3b50e7f4302a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
