"""Added the initial migration

Revision ID: beae5a241c3b
Revises: bf45fcbe317f
Create Date: 2024-12-25 11:56:38.395413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beae5a241c3b'
down_revision: Union[str, None] = 'bf45fcbe317f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
