"""Added the initial migration

Revision ID: c7551e4d1ee1
Revises: 94bc95bf82ee
Create Date: 2024-12-21 00:31:31.533719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7551e4d1ee1'
down_revision: Union[str, None] = '94bc95bf82ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
