"""Added the initial migration

Revision ID: ed4f1be2bd00
Revises: 7c6277dcb1b8
Create Date: 2025-01-06 18:58:42.150379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4f1be2bd00'
down_revision: Union[str, None] = '7c6277dcb1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
